# Setup
title:        Tryon Learning
tagline:      Children's education rethought for mobile
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Tryon Learning LLC
  url:        http://tryonlearning.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown