# Setup
title:        Tryon Learning
tagline:      Children's education rethought on mobile
baseurl:      "/tryonlearning"
paginate:     1

# About/contact
author:
  name:       Tryon Learning LLC
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown